#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0

# Environment Variables that need to be set to use this file
#
#   COMPOSE_PROJECT_NAME - This is used to ensure all chaincode containers are running on the same network
#                          as the peers, orderer, and ca. The only requirement is that this is set to
#                          some string and cannot be left blank. To match with the default FPC network,
#                          use `fabric-fpc`.
#
#
# NOTE: To use the version of the fabric-gateway or the frontend on the host machine, uncomment
# the respective volumes section in the services
#

version: '2'

networks:
  basic:

services:
  auction_client:
    container_name: auction_client
    image: hyperledger/fabric-private-chaincode-auction_client_backend:${FPC_VERSION}
    build:
      context: client/backend/fabric-gateway
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: npm start
    # volumes:
      # - ${DOCKERD_FPC_PATH}/demo/client/backend/fabric-gateway/src:/usr/src/app/src
      # - ${DOCKERD_FPC_PATH}/demo/client/backend/fabric-gateway/config.json:/usr/src/app/config.json

  auction_frontend:
    container_name: auction_frontend
    image: hyperledger/fabric-private-chaincode-auction_frontend:${FPC_VERSION}
    build:
      context: client/frontend
    ports:
      - "5000:5000"
    # volumes:
    #   - ${DOCKERD_FPC_PATH}/demo/client/frontend/src:/usr/src/app/src
    depends_on:
      - auction_client

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_basic
