# Copyright IBM Corp. All Rights Reserved.
# Copyright 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  #  org1
  ecc.peer0.org1.example.com:
    container_name: ecc.peer0.org1.example.com
    hostname: ecc.peer0.org1.example.com
    image: fpc/ecc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ecc.peer0.org1.example.com:9999
      - CHAINCODE_ID=ecc_1.0:2c4f49232cae2fdd5f86c035659c7a0a2476ba6ec7ff7aba8cad48d84a07cdba
      - FABRIC_LOGGING_SPEC=DEBUG
    networks:
      - default

  ercc.peer0.org1.example.com:
    container_name: ercc.peer0.org1.example.com
    hostname: ercc.peer0.org1.example.com
    image: fpc/ercc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ercc.peer0.org1.example.com:9999
      - CHAINCODE_ID=ercc_1.0:db8357401a6d9cb34e6cd0c820fab21694bdff788f2c9931ffe5827e2d71668f
      - FABRIC_LOGGING_SPEC=DEBUG
    networks:
      - default

  # org2
  ecc.peer0.org2.example.com:
    container_name: ecc.peer0.org2.example.com
    hostname: ecc.peer0.org2.example.com
    image: fpc/ecc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ecc.peer0.org2.example.com:9999
      - CHAINCODE_ID=ecc_1.0:2c4f49232cae2fdd5f86c035659c7a0a2476ba6ec7ff7aba8cad48d84a07cdba
      - FABRIC_LOGGING_SPEC=DEBUG
    networks:
      - default

  ercc.peer0.org2.example.com:
    container_name: ercc.peer0.org2.example.com
    hostname: ercc.peer0.org2.example.com
    image: fpc/ercc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ercc.peer0.org2.example.com:9999
      - CHAINCODE_ID=ercc_1.0:db8357401a6d9cb34e6cd0c820fab21694bdff788f2c9931ffe5827e2d71668f
      - FABRIC_LOGGING_SPEC=DEBUG
    networks:
      - default

networks:
  default:
    external:
      name: net_test
